const basketLinesConstants = {
    GET_REQUEST: 'BASKET_LIST_GET_REQUEST',
    GET_SUCCESS: 'BASKET_LIST_GET_SUCCESS',
    GET_FAILURE: 'BASKET_LIST_GET_FAILURE',

    ADD_REQUEST: 'ADD_BOOK_TO_BASKET_LIST_GET_REQUEST',
    ADD_SUCCESS: 'ADD_BOOK_TO_BASKET_LIST_GET_SUCCESS',
    ADD_FAILURE: 'ADD_BOOK_TO_BASKET_LIST_GET_FAILURE',

    REMOVE_REQUEST: 'REMOVE_BOOK_FROM_BASKET_GET_REQUEST',
    REMOVE_SUCCESS: 'REMOVE_BOOK_FROM_BASKET_GET_SUCCESS',
    REMOVE_FAILURE: 'REMOVE_BOOK_FROM_BASKET_GET_FAILURE',

    UPDATE_COUNT_REQUEST: 'UPDATE_COUNT_BOOKS_IN_BASKET_GET_REQUEST',
    UPDATE_COUNT_SUCCESS: 'UPDATE_COUNT_BOOKS_IN_BASKET_GET_SUCCESS',
    UPDATE_COUNT_FAILURE: 'UPDATE_COUNT_BOOKS_IN_BASKET_GET_FAILURE',

    ORDER_REQUEST: 'ORDER_BASKET_BOOKS_REQUEST',
    ORDER_SUCCESS: 'ORDER_BASKET_BOOKS_SUCCESS',
    ORDER_FAILURE: 'ORDER_BASKET_BOOKS_FAILURE'
};

const basketLinesStatuses = {
    BASKET_EMPTY: 'BASKET_LIST_EMPTY',  
    GET_BASKET_REQUEST: 'GET_BASKET_LIST_REQUEST',
    ADD_BOOK_TO_BASKET_REQUEST: 'ADD_BOOK_TO_BASKET_LIST_REQUEST',
    REMOVE_BOOK_FROM_BASKET_REQUEST: 'REMOVE_BOOK_FROM_BASKET_LIST_REQUEST',
    UPDATE_BOOK_COUNT_IN_BASKET_REQUEST: 'UPDATE_BOOK_COUNT_IN_BASKET_REQUEST',
    ORDER_BOOKS_REQUEST: 'ORDER_LIST_BOOKS_REQUEST',
    SUCCESS: 'BASKET_LIST_REQUEST_SUCCESS',
};

export default  basketLinesConstants;
export { basketLinesStatuses }
