const orderConstants = {
    GET_REQUEST: 'ORDER_LIST_GET_REQUEST',
    GET_SUCCESS: 'ORDER_LIST_GET_SUCCESS',
    GET_FAILURE: 'ORDER_LIST_GET_FAILURE',

    REMOVE_REQUEST: 'REMOVE_BOOK_FROM_ORDER_GET_REQUEST',
    REMOVE_SUCCESS: 'REMOVE_BOOK_FROM_ORDER_GET_SUCCESS',
    REMOVE_FAILURE: 'REMOVE_BOOK_FROM_ORDER_GET_FAILURE',

    UPDATE_COUNT_REQUEST: 'UPDATE_COUNT_BOOKS_IN_ORDER_GET_REQUEST',
    UPDATE_COUNT_SUCCESS: 'UPDATE_COUNT_BOOKS_IN_ORDER_GET_SUCCESS',
    UPDATE_COUNT_FAILURE: 'UPDATE_COUNT_BOOKS_IN_ORDER_GET_FAILURE',

    GIVE_ALL_REQUEST: 'GIVE_ALL_BOOKS_ORDER_REQUEST',
    GIVE_ALL_SUCCESS: 'GIVE_ALL_BOOKS_ORDER_SUCCESS',
    GIVE_ALL_FAILURE: 'GIVE_ALL_BOOKS_ORDER_FAILURE',

    GIVE_REQUEST: 'GIVE_BOOKS_ORDER_REQUEST',
    GIVE_SUCCESS: 'GIVE_BOOKS_ORDER_SUCCESS',
    GIVE_FAILURE: 'GIVE_BOOKS_ORDER_FAILURE'
};

const orderStatuses = {
    ORDER_EMPTY: 'ORDER_LIST_EMPTY',  
    GET_ORDER_REQUEST: 'GET_ORDER_LIST_REQUEST',
    REMOVE_BOOK_FROM_ORDER_REQUEST: 'REMOVE_BOOK_FROM_ORDER_LIST_REQUEST',
    UPDATE_BOOK_COUNT_IN_ORDER_REQUEST: 'UPDATE_BOOK_COUNT_IN_ORDER_REQUEST',
    GIVE_BOOK_REQUEST: 'GIVE_BOOK_REQUEST',
    GIVE_ALL_BOOKS_REQUEST: 'GIVE_ALL_BOOKS_REQUEST',
    SUCCESS: 'ORDER_LIST_REQUEST_SUCCESS',
};

export default  orderConstants;
export { orderStatuses }
